blog/urls.py
# blog/urls.py
from django.urls import path
from . import views
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('', views.home_page, name='post-list'),
    path('posts/', views.PostListView.as_view(), name='post-list'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('posts/create/', views.CreatePost.as_view(), name='post-create'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homeblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from users.views import LoginView, LogoutView, RegisterView, UserProfileView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<str:username>/', UserProfileView.as_view(), name='profile'),
]

users/models.py
from django.db import models


# Create your models here.
class user(models.Model):
    username = models.CharField(max_length=30, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=128)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    icon = models.ImageField(upload_to='user_icons/', blank=True, null=True)

users/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

from users.models import user
from blog.models import Post, Comment


# Create your views here.

class RegisterView(generic.View):
    def get(self, request):
        form = UserCreationForm()
        return render(request, 'users/register.html', {'form': form})
    
    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect(reverse('blog:post-list'))
        return render(request, 'users/register.html', {'form': form})
    
class LoginView(generic.View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, 'users/login.html', {'form': form})

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return HttpResponseRedirect(reverse('blog:post-list'))
        return render(request, 'users/login.html', {'form': form})
    
class LogoutView(generic.View):
    def get(self, request):
        logout(request)
        return render(request, 'users/logout.html')
    
    def post(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('blog:post-list'))
    
# class UserProfileView(generic.DetailView):
#     model = User
#     template_name = 'users/profile.html'
#     context_object_name = 'user'

#     def get_object(self, queryset=None):
#         return get_object_or_404(user, username=self.kwargs['username'])
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['posts'] = self.object.post_set.all()
#         return context
class UserProfileView(generic.DetailView):
    model = User
    template_name = 'users/profile.html'
    

    def get(self, request, *args, **kwargs):
        username = self.kwargs.get('username')
        user = get_object_or_404(User, username=username)
        posts = Post.objects.filter(author=user)
        return render(request, self.template_name, {'user': user, 'posts': posts})

@login_required
def profile_view(request, username):
    user = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=user)
    return render(request, 'users/profile.html', {'user': user, 'posts': posts})

users/templates/users/login.html
{% load static %}


<link rel="stylesheet" href="{% static 'logincss.css' %}">
<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    <h1 class="center">Login</h1>
    <div class="center">
        <div class="form-group">
            <p>Please enter your credentials to login.</p>
            <label for="username">Username:</label>
            <input type="text" name="username" id="username" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" name="password" id="password" class="form-control" required>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Login</button>
        </div>
    </div>
</form>

users/templates/users/logout.html
{% csrf_token %}
<form method="post" action="{% url 'users:logout' %}"></form>

users/templates/users/profile.html
{% extends "base.html" %}
{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'profilecss.css' %}">

<a href="{% url 'users:profile' username=user.username %}"></a>
<div class="profile-container">
    <h1 class="center">Profile</h1>
    <div class="profile-info">
        <p><strong>Username:</strong> {{ user.username }}</p> 
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>First Name:</strong> {{ user.first_name }}</p>
        <p><strong>Last Name:</strong> {{ user.last_name }}</p>
    </div>

<h2>{{ user.username }}'s Posts</h2>
<ul>
    {% for post in posts %}
        <li>
           
            <a href="{% url 'blog:post-detail' post.pk %}">{{ post.title }}</a>
            <p><strong>Published:</strong> {{ post.created_at|date:"F j, Y" }}</p>
            <p>{{ post.content|truncatewords:20 }}</p>
        </li>
    {% empty %}
        <li>No posts yet.</li>
    {% endfor %}
</ul>
{% endblock %}

users/templates/users/register.html
<h2>Register</h2>
<form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">submit</button>
</form>